name: YunP4n_Sec

on:
  schedule:
    - cron: '0 1,6,9 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  github_monitor:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Python3
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: clean data
        run: echo "CleanKeywords=$(cat ./clean.txt)" >> $GITHUB_ENV

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./requirements.txt
      
      - name: Run YunP4n_Sec
        env:
          keywords: '红蓝对抗 hvv 护网 CVE RCE CNVD QVD 未授权 命令执行 安全工具 漏洞利用工具 ExploitGUI poc cobaltstrike BOF &exp  java安全 web安全 云安全 应急响应 安全检测 后渗透 内网渗透 远控 免杀 资产测绘 渗透测试 漏洞扫描 内网渗透 代码审计 漏洞挖掘 Kubernetes攻防 指纹识别 红队工具 蜜罐 钓鱼 威胁情报 CMS漏洞 信息泄漏 信息收集 安全研究'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          secretKey: ${{ secrets.DINGDING_SECRETKEY }}
          secretKey2: ${{ secrets.DINGDING_SECRETKEY_2 }}
          webhook: ${{ secrets.DINGDING_WEBHOOK }}
          webhook2: ${{ secrets.DINGDING_WEBHOOK_2 }}
        run: python3 ./main.py

      - name: test run
        run: echo ${{ env.CleanKeywords }}

      - name: push clean data
        run: |
          echo ${{ env.CleanKeywords }} > ./clean.txt
          REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add .
          git commit -m "Add new comment"
          git push ${REMOTE} main
